[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/experiment-1"
  to = "/Experiment%201/index.html"
  status = 200

[[redirects]]
  from = "/experiment-2"
  to = "/Experiment%202/index.html"
  status = 200

[[redirects]]
  from = "/exp1"
  to = "/Experiment%201/index.html"
  status = 200

[[redirects]]
  from = "/exp2"
  to = "/Experiment%202/index.html"
  status = 200

[[redirects]]
  from = "/exp1.1"
  to = "/Experiment%201/exp1.1/1.1.html"
  status = 200

[[redirects]]
  from = "/exp1.2"
  to = "/Experiment%201/exp1.2/1.2.html"
  status = 200

[[redirects]]
  from = "/exp1.3"
  to = "/Experiment%201/exp1.3/1.3.html"
  status = 200

[[redirects]]
  from = "/exp2.1"
  to = "/Experiment%202/exp%201.2.1/2.1.html"
  status = 200

[[redirects]]
  from = "/exp2.2"
  to = "/Experiment%202/exp%201.2.2/exp2.2.html"
  status = 200

[[redirects]]
  from = "/exp2.3"
  to = "/Experiment%202/exp%201.2.3/exp1.2.3.html"
  status = 200
